In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("50_Startups.csv")

In [3]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [5]:
dataset["Administration"].fillna(dataset["Administration"].mode()[0], inplace=True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mode()[0], inplace=True)

In [6]:
dataset.head(12)

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87             0.00  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08        51283.14        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40

In [7]:
x = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4:5].values

In [8]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 0.0, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 51283.14, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 294919.57, '

In [9]:
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

In [10]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [11]:
dataset["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [12]:
# 0-California, 1-Florida, 2-New York

In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh", OneHotEncoder(), [3])],remainder="passthrough")
x = ct.fit_transform(x)

In [14]:
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 0.0],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 51283.14, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58, 28257

In [15]:
x.shape

(50, 6)

In [16]:
y.shape

(50, 1)

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=1)

In [18]:
x_train.shape

(35, 6)

In [19]:
y_train.shape

(35, 1)

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [22]:
regression = Sequential()

In [23]:
regression.add(Dense(units = 6, kernel_initializer = "random_uniform",activation = "relu")) #x_train, 1st hidden layer

In [24]:
regression.add(Dropout(0.2))

In [25]:
regression.add(Dense(units = 12, kernel_initializer = "random_uniform",activation = "relu")) #x_train, 2nd hidden layer

In [26]:
regression.add(Dropout(0.2))

In [27]:
regression.add(Dense(units = 12, kernel_initializer = "random_uniform",activation = "relu")) #x_train, 3rd hidden layer

In [28]:
regression.add(Dropout(0.2))

In [29]:
regression.add(Dense(units = 12, kernel_initializer = "random_uniform",activation = "relu")) #x_train, 4th hidden layer

In [30]:
regression.add(Dense(units = 1, kernel_initializer = "random_uniform",activation = "relu")) #x_train

In [31]:
regression.compile(optimizer = "adam", loss = "mse", metrics = ['mse'])

In [62]:
history = regression.fit(x_train,y_train, batch_size=50, epochs = 800)

Epoch 1/800
1/1 [==============================] - 0s 3ms/step - loss: 1393175808.0000 - mse: 1393175808.0000
Epoch 2/800
1/1 [==============================] - 0s 5ms/step - loss: 850625536.0000 - mse: 850625536.0000
Epoch 3/800
1/1 [==============================] - 0s 5ms/step - loss: 1708263424.0000 - mse: 1708263424.0000
Epoch 4/800
1/1 [==============================] - 0s 3ms/step - loss: 1544096256.0000 - mse: 1544096256.0000
Epoch 5/800
1/1 [==============================] - 0s 5ms/step - loss: 1220299520.0000 - mse: 1220299520.0000
Epoch 6/800
1/1 [==============================] - 0s 3ms/step - loss: 1727603328.0000 - mse: 1727603328.0000
Epoch 7/800
1/1 [==============================] - 0s 13ms/step - loss: 2472833792.0000 - mse: 2472833792.0000
Epoch 8/800
1/1 [==============================] - 0s 13ms/step - loss: 1109776512.0000 - mse: 1109776512.0000
Epoch 9/800
1/1 [==============================] - 0s 12ms/step - loss: 2091015552.0000 - mse: 2091015552.0000
Epoch 10/

1/1 [==============================] - 0s 3ms/step - loss: 1627964544.0000 - mse: 1627964544.0000
Epoch 75/800
1/1 [==============================] - 0s 6ms/step - loss: 1100814080.0000 - mse: 1100814080.0000
Epoch 76/800
1/1 [==============================] - 0s 4ms/step - loss: 1033226880.0000 - mse: 1033226880.0000
Epoch 77/800
1/1 [==============================] - 0s 3ms/step - loss: 1768321664.0000 - mse: 1768321664.0000
Epoch 78/800
1/1 [==============================] - 0s 4ms/step - loss: 1356084224.0000 - mse: 1356084224.0000
Epoch 79/800
1/1 [==============================] - 0s 7ms/step - loss: 893113536.0000 - mse: 893113536.0000
Epoch 80/800
1/1 [==============================] - 0s 5ms/step - loss: 1390957312.0000 - mse: 1390957312.0000
Epoch 81/800
1/1 [==============================] - 0s 3ms/step - loss: 1451639040.0000 - mse: 1451639040.0000
Epoch 82/800
1/1 [==============================] - 0s 3ms/step - loss: 2123343232.0000 - mse: 2123343232.0000
Epoch 83/800
1/1

1/1 [==============================] - 0s 3ms/step - loss: 1249239296.0000 - mse: 1249239296.0000
Epoch 148/800
1/1 [==============================] - 0s 6ms/step - loss: 1981478656.0000 - mse: 1981478656.0000
Epoch 149/800
1/1 [==============================] - 0s 4ms/step - loss: 1422781056.0000 - mse: 1422781056.0000
Epoch 150/800
1/1 [==============================] - 0s 5ms/step - loss: 1336044928.0000 - mse: 1336044928.0000
Epoch 151/800
1/1 [==============================] - 0s 4ms/step - loss: 849663168.0000 - mse: 849663168.0000
Epoch 152/800
1/1 [==============================] - 0s 6ms/step - loss: 1898082816.0000 - mse: 1898082816.0000
Epoch 153/800
1/1 [==============================] - 0s 4ms/step - loss: 2161176832.0000 - mse: 2161176832.0000
Epoch 154/800
1/1 [==============================] - 0s 4ms/step - loss: 970353728.0000 - mse: 970353728.0000
Epoch 155/800
1/1 [==============================] - 0s 2ms/step - loss: 1763324544.0000 - mse: 1763324544.0000
Epoch 156/

1/1 [==============================] - 0s 13ms/step - loss: 1066079744.0000 - mse: 1066079744.0000
Epoch 221/800
1/1 [==============================] - 0s 6ms/step - loss: 1106185472.0000 - mse: 1106185472.0000
Epoch 222/800
1/1 [==============================] - 0s 10ms/step - loss: 2099163008.0000 - mse: 2099163008.0000
Epoch 223/800
1/1 [==============================] - 0s 7ms/step - loss: 1229971840.0000 - mse: 1229971840.0000
Epoch 224/800
1/1 [==============================] - 0s 5ms/step - loss: 1748977920.0000 - mse: 1748977920.0000
Epoch 225/800
1/1 [==============================] - 0s 10ms/step - loss: 1400593792.0000 - mse: 1400593792.0000
Epoch 226/800
1/1 [==============================] - 0s 6ms/step - loss: 1398008320.0000 - mse: 1398008320.0000
Epoch 227/800
1/1 [==============================] - 0s 7ms/step - loss: 1206855680.0000 - mse: 1206855680.0000
Epoch 228/800
1/1 [==============================] - 0s 2ms/step - loss: 1786121984.0000 - mse: 1786121984.0000
Epo

1/1 [==============================] - 0s 6ms/step - loss: 1482835328.0000 - mse: 1482835328.0000
Epoch 294/800
1/1 [==============================] - 0s 3ms/step - loss: 1285169792.0000 - mse: 1285169792.0000
Epoch 295/800
1/1 [==============================] - 0s 5ms/step - loss: 1124168320.0000 - mse: 1124168320.0000
Epoch 296/800
1/1 [==============================] - 0s 4ms/step - loss: 1168162176.0000 - mse: 1168162176.0000
Epoch 297/800
1/1 [==============================] - 0s 4ms/step - loss: 1535709824.0000 - mse: 1535709824.0000
Epoch 298/800
1/1 [==============================] - 0s 4ms/step - loss: 1835471744.0000 - mse: 1835471744.0000
Epoch 299/800
1/1 [==============================] - 0s 4ms/step - loss: 1534581632.0000 - mse: 1534581632.0000
Epoch 300/800
1/1 [==============================] - 0s 4ms/step - loss: 1586206592.0000 - mse: 1586206592.0000
Epoch 301/800
1/1 [==============================] - 0s 5ms/step - loss: 1792494080.0000 - mse: 1792494080.0000
Epoch 

1/1 [==============================] - 0s 3ms/step - loss: 1115770112.0000 - mse: 1115770112.0000
Epoch 367/800
1/1 [==============================] - 0s 4ms/step - loss: 1484765696.0000 - mse: 1484765696.0000
Epoch 368/800
1/1 [==============================] - 0s 3ms/step - loss: 1706559488.0000 - mse: 1706559488.0000
Epoch 369/800
1/1 [==============================] - 0s 3ms/step - loss: 1523310848.0000 - mse: 1523310848.0000
Epoch 370/800
1/1 [==============================] - 0s 5ms/step - loss: 1155840640.0000 - mse: 1155840640.0000
Epoch 371/800
1/1 [==============================] - 0s 3ms/step - loss: 1732210048.0000 - mse: 1732210048.0000
Epoch 372/800
1/1 [==============================] - 0s 4ms/step - loss: 1511792128.0000 - mse: 1511792128.0000
Epoch 373/800
1/1 [==============================] - 0s 5ms/step - loss: 1658215808.0000 - mse: 1658215808.0000
Epoch 374/800
1/1 [==============================] - 0s 4ms/step - loss: 1263074176.0000 - mse: 1263074176.0000
Epoch 

1/1 [==============================] - 0s 5ms/step - loss: 1229486080.0000 - mse: 1229486080.0000
Epoch 439/800
1/1 [==============================] - 0s 7ms/step - loss: 1888764800.0000 - mse: 1888764800.0000
Epoch 440/800
1/1 [==============================] - 0s 10ms/step - loss: 1775486848.0000 - mse: 1775486848.0000
Epoch 441/800
1/1 [==============================] - 0s 3ms/step - loss: 1338563584.0000 - mse: 1338563584.0000
Epoch 442/800
1/1 [==============================] - 0s 4ms/step - loss: 1128817408.0000 - mse: 1128817408.0000
Epoch 443/800
1/1 [==============================] - 0s 7ms/step - loss: 1562349312.0000 - mse: 1562349312.0000
Epoch 444/800
1/1 [==============================] - 0s 6ms/step - loss: 1425733504.0000 - mse: 1425733504.0000
Epoch 445/800
1/1 [==============================] - 0s 7ms/step - loss: 2309623296.0000 - mse: 2309623296.0000
Epoch 446/800
1/1 [==============================] - 0s 4ms/step - loss: 1428430080.0000 - mse: 1428430080.0000
Epoch

1/1 [==============================] - 0s 4ms/step - loss: 1612003584.0000 - mse: 1612003584.0000
Epoch 512/800
1/1 [==============================] - 0s 2ms/step - loss: 2381595392.0000 - mse: 2381595392.0000
Epoch 513/800
1/1 [==============================] - 0s 5ms/step - loss: 1241445760.0000 - mse: 1241445760.0000
Epoch 514/800
1/1 [==============================] - 0s 3ms/step - loss: 1505728384.0000 - mse: 1505728384.0000
Epoch 515/800
1/1 [==============================] - 0s 4ms/step - loss: 1370455040.0000 - mse: 1370455040.0000
Epoch 516/800
1/1 [==============================] - 0s 3ms/step - loss: 1324262272.0000 - mse: 1324262272.0000
Epoch 517/800
1/1 [==============================] - 0s 4ms/step - loss: 1553473408.0000 - mse: 1553473408.0000
Epoch 518/800
1/1 [==============================] - 0s 3ms/step - loss: 1316696192.0000 - mse: 1316696192.0000
Epoch 519/800
1/1 [==============================] - 0s 3ms/step - loss: 872290240.0000 - mse: 872290240.0000
Epoch 52

1/1 [==============================] - 0s 2ms/step - loss: 1340686848.0000 - mse: 1340686848.0000
Epoch 585/800
1/1 [==============================] - 0s 4ms/step - loss: 1915622016.0000 - mse: 1915622016.0000
Epoch 586/800
1/1 [==============================] - 0s 4ms/step - loss: 1382814336.0000 - mse: 1382814336.0000
Epoch 587/800
1/1 [==============================] - 0s 3ms/step - loss: 1476359680.0000 - mse: 1476359680.0000
Epoch 588/800
1/1 [==============================] - 0s 3ms/step - loss: 1127718528.0000 - mse: 1127718528.0000
Epoch 589/800
1/1 [==============================] - 0s 4ms/step - loss: 2130503040.0000 - mse: 2130503040.0000
Epoch 590/800
1/1 [==============================] - 0s 3ms/step - loss: 1395908224.0000 - mse: 1395908224.0000
Epoch 591/800
1/1 [==============================] - 0s 5ms/step - loss: 1227476608.0000 - mse: 1227476608.0000
Epoch 592/800
1/1 [==============================] - 0s 3ms/step - loss: 1252509952.0000 - mse: 1252509952.0000
Epoch 

1/1 [==============================] - 0s 4ms/step - loss: 1232011264.0000 - mse: 1232011264.0000
Epoch 658/800
1/1 [==============================] - 0s 3ms/step - loss: 1595938944.0000 - mse: 1595938944.0000
Epoch 659/800
1/1 [==============================] - 0s 121ms/step - loss: 1599979520.0000 - mse: 1599979520.0000
Epoch 660/800
1/1 [==============================] - 0s 4ms/step - loss: 1807889408.0000 - mse: 1807889408.0000
Epoch 661/800
1/1 [==============================] - 0s 5ms/step - loss: 1059337600.0000 - mse: 1059337600.0000
Epoch 662/800
1/1 [==============================] - 0s 5ms/step - loss: 1528516224.0000 - mse: 1528516224.0000
Epoch 663/800
1/1 [==============================] - 0s 4ms/step - loss: 1726581376.0000 - mse: 1726581376.0000
Epoch 664/800
1/1 [==============================] - 0s 6ms/step - loss: 1237544320.0000 - mse: 1237544320.0000
Epoch 665/800
1/1 [==============================] - 0s 6ms/step - loss: 1628822912.0000 - mse: 1628822912.0000
Epoc

1/1 [==============================] - 0s 5ms/step - loss: 1835657600.0000 - mse: 1835657600.0000
Epoch 731/800
1/1 [==============================] - 0s 3ms/step - loss: 1772947456.0000 - mse: 1772947456.0000
Epoch 732/800
1/1 [==============================] - 0s 3ms/step - loss: 1631495168.0000 - mse: 1631495168.0000
Epoch 733/800
1/1 [==============================] - 0s 4ms/step - loss: 1731124096.0000 - mse: 1731124096.0000
Epoch 734/800
1/1 [==============================] - 0s 2ms/step - loss: 1126622976.0000 - mse: 1126622976.0000
Epoch 735/800
1/1 [==============================] - 0s 2ms/step - loss: 1938681472.0000 - mse: 1938681472.0000
Epoch 736/800
1/1 [==============================] - 0s 3ms/step - loss: 1455560064.0000 - mse: 1455560064.0000
Epoch 737/800
1/1 [==============================] - 0s 4ms/step - loss: 1433167232.0000 - mse: 1433167232.0000
Epoch 738/800
1/1 [==============================] - 0s 5ms/step - loss: 2018322688.0000 - mse: 2018322688.0000
Epoch 

In [63]:
ypred = regression.predict(x_test)

In [64]:
ypred

array([[112442.125],
       [ 81053.36 ],
       [ 87368.31 ],
       [ 56772.72 ],
       [189354.52 ],
       [181148.23 ],
       [ 36983.59 ],
       [ 90710.164],
       [ 94898.766],
       [ 85464.96 ],
       [107429.44 ],
       [ 94282.33 ],
       [114069.555],
       [101333.08 ],
       [103406.28 ]], dtype=float32)

In [65]:
ypred>0.5

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [66]:
y_test

array([[105008.31],
       [ 96479.51],
       [ 78239.91],
       [ 81229.06],
       [191050.39],
       [182901.99],
       [ 35673.41],
       [101004.64],
       [ 49490.75],
       [ 97483.56],
       [ 97427.84],
       [ 81005.76],
       [111313.02],
       [ 90708.19],
       [122776.86]])

In [67]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,ypred)

In [68]:
accuracy

0.8290713365030661

In [69]:
yp = regression.predict(sc.transform([[0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42]]))

In [70]:
yp

array([[178392.73]], dtype=float32)

In [71]:
yp>0.5

array([[ True]])

In [72]:
yp = regression.predict(sc.transform([[0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68]]))

In [73]:
yp

array([[165915.64]], dtype=float32)

In [74]:
yp>0.5

array([[ True]])

In [75]:
regression.save('regression.h5')

In [76]:
regression.save("profit.h5")

In [77]:
import joblib
joblib.dump(ct, "column")

['column']

In [78]:
import joblib
joblib.dump(sc, "scaler")

['scaler']