In [1]:
import numpy as np
import pandas as pd
#pd.options.display.float_format = '{:.2f}'.format

In [2]:
dataset = pd.read_csv("Fish.csv")

In [3]:
dataset

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [4]:
dataset.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [5]:
x = dataset.iloc[:,1:7].values
y = dataset.iloc[:,0:1].values

In [6]:
dataset.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [7]:
x

array([[2.42000e+02, 2.32000e+01, 2.54000e+01, 3.00000e+01, 1.15200e+01,
        4.02000e+00],
       [2.90000e+02, 2.40000e+01, 2.63000e+01, 3.12000e+01, 1.24800e+01,
        4.30560e+00],
       [3.40000e+02, 2.39000e+01, 2.65000e+01, 3.11000e+01, 1.23778e+01,
        4.69610e+00],
       [3.63000e+02, 2.63000e+01, 2.90000e+01, 3.35000e+01, 1.27300e+01,
        4.45550e+00],
       [4.30000e+02, 2.65000e+01, 2.90000e+01, 3.40000e+01, 1.24440e+01,
        5.13400e+00],
       [4.50000e+02, 2.68000e+01, 2.97000e+01, 3.47000e+01, 1.36024e+01,
        4.92740e+00],
       [5.00000e+02, 2.68000e+01, 2.97000e+01, 3.45000e+01, 1.41795e+01,
        5.27850e+00],
       [3.90000e+02, 2.76000e+01, 3.00000e+01, 3.50000e+01, 1.26700e+01,
        4.69000e+00],
       [4.50000e+02, 2.76000e+01, 3.00000e+01, 3.51000e+01, 1.40049e+01,
        4.84380e+00],
       [5.00000e+02, 2.85000e+01, 3.07000e+01, 3.62000e+01, 1.42266e+01,
        4.95940e+00],
       [4.75000e+02, 2.84000e+01, 3.10000e+01, 3.6

In [8]:
y

array([['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['W

In [9]:
dataset["Species"].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [10]:
# 0-Bream, 1-Parkki, 2-Perch, 3-Pike, 4-Roach, 5-Smel, 6-Whitefish

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh", OneHotEncoder(), [0])],remainder="passthrough")
y = ct.fit_transform(y).toarray()

In [12]:
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [13]:
y.shape

(159, 7)

In [14]:
print(y)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=1)

In [16]:
x_train.shape

(111, 6)

In [17]:
y_train.shape

(111, 7)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [20]:
categorical = Sequential()

In [21]:
categorical.add(Dense(units = 6, kernel_initializer = "random_uniform",activation = "relu")) #x_train

In [22]:
categorical.add(Dropout(0.2))

In [23]:
categorical.add(Dense(units = 12, kernel_initializer = "random_uniform",activation = "relu"))

In [24]:
categorical.add(Dropout(0.2))

In [25]:
categorical.add(Dense(units = 12, kernel_initializer = "random_uniform",activation = "relu"))

In [26]:
categorical.add(Dropout(0.2))

In [27]:
categorical.add(Dense(units = 12, kernel_initializer = "random_uniform",activation = "relu"))

In [28]:
categorical.add(Dense(units = 7, kernel_initializer = "random_uniform",activation = "softmax")) #y_train

In [29]:
categorical.compile(optimizer = "rmsprop", loss = "categorical_crossentropy", metrics = ["accuracy"])

In [30]:
history = categorical.fit(x_train,y_train, batch_size=64, epochs = 1000, validation_data = (x_test,y_test))

Epoch 1/1000
2/2 [==============================] - 1s 151ms/step - loss: 1.9451 - accuracy: 0.2703 - val_loss: 1.9416 - val_accuracy: 0.4167
Epoch 2/1000
2/2 [==============================] - 0s 20ms/step - loss: 1.9420 - accuracy: 0.3243 - val_loss: 1.9387 - val_accuracy: 0.4167
Epoch 3/1000
2/2 [==============================] - 0s 24ms/step - loss: 1.9398 - accuracy: 0.3243 - val_loss: 1.9362 - val_accuracy: 0.4167
Epoch 4/1000
2/2 [==============================] - 0s 28ms/step - loss: 1.9379 - accuracy: 0.3243 - val_loss: 1.9337 - val_accuracy: 0.4167
Epoch 5/1000
2/2 [==============================] - 0s 24ms/step - loss: 1.9359 - accuracy: 0.3243 - val_loss: 1.9312 - val_accuracy: 0.4167
Epoch 6/1000
2/2 [==============================] - 0s 23ms/step - loss: 1.9339 - accuracy: 0.3243 - val_loss: 1.9287 - val_accuracy: 0.4167
Epoch 7/1000
2/2 [==============================] - 0s 41ms/step - loss: 1.9320 - accuracy: 0.3243 - val_loss: 1.9262 - val_accuracy: 0.4167
Epoch 8/1000

Epoch 59/1000
2/2 [==============================] - 0s 22ms/step - loss: 1.7044 - accuracy: 0.3243 - val_loss: 1.6732 - val_accuracy: 0.4167
Epoch 60/1000
2/2 [==============================] - 0s 21ms/step - loss: 1.7013 - accuracy: 0.3243 - val_loss: 1.6717 - val_accuracy: 0.4167
Epoch 61/1000
2/2 [==============================] - 0s 23ms/step - loss: 1.7131 - accuracy: 0.3243 - val_loss: 1.6699 - val_accuracy: 0.4167
Epoch 62/1000
2/2 [==============================] - 0s 27ms/step - loss: 1.7240 - accuracy: 0.3243 - val_loss: 1.6700 - val_accuracy: 0.4167
Epoch 63/1000
2/2 [==============================] - 0s 23ms/step - loss: 1.7029 - accuracy: 0.3243 - val_loss: 1.6678 - val_accuracy: 0.4167
Epoch 64/1000
2/2 [==============================] - 0s 23ms/step - loss: 1.6901 - accuracy: 0.3243 - val_loss: 1.6657 - val_accuracy: 0.4167
Epoch 65/1000
2/2 [==============================] - 0s 24ms/step - loss: 1.6956 - accuracy: 0.3243 - val_loss: 1.6652 - val_accuracy: 0.4167
Epoch 

2/2 [==============================] - 0s 46ms/step - loss: 1.5357 - accuracy: 0.4054 - val_loss: 1.5931 - val_accuracy: 0.5417
Epoch 174/1000
2/2 [==============================] - 0s 20ms/step - loss: 1.5333 - accuracy: 0.3874 - val_loss: 1.5916 - val_accuracy: 0.5417
Epoch 175/1000
2/2 [==============================] - 0s 26ms/step - loss: 1.5378 - accuracy: 0.3694 - val_loss: 1.5903 - val_accuracy: 0.5417
Epoch 176/1000
2/2 [==============================] - 0s 42ms/step - loss: 1.5811 - accuracy: 0.3153 - val_loss: 1.5897 - val_accuracy: 0.5208
Epoch 177/1000
2/2 [==============================] - 0s 22ms/step - loss: 1.5588 - accuracy: 0.3514 - val_loss: 1.5873 - val_accuracy: 0.5208
Epoch 178/1000
2/2 [==============================] - 0s 23ms/step - loss: 1.5265 - accuracy: 0.3784 - val_loss: 1.5851 - val_accuracy: 0.5417
Epoch 179/1000
2/2 [==============================] - 0s 20ms/step - loss: 1.5307 - accuracy: 0.3514 - val_loss: 1.5851 - val_accuracy: 0.5417
Epoch 180/1000

2/2 [==============================] - 0s 19ms/step - loss: 1.4874 - accuracy: 0.3423 - val_loss: 1.5045 - val_accuracy: 0.5417
Epoch 231/1000
2/2 [==============================] - 0s 47ms/step - loss: 1.4990 - accuracy: 0.3604 - val_loss: 1.5002 - val_accuracy: 0.5417
Epoch 232/1000
2/2 [==============================] - 0s 24ms/step - loss: 1.4741 - accuracy: 0.3604 - val_loss: 1.4988 - val_accuracy: 0.5417
Epoch 233/1000
2/2 [==============================] - 0s 20ms/step - loss: 1.4978 - accuracy: 0.3423 - val_loss: 1.4993 - val_accuracy: 0.5417
Epoch 234/1000
2/2 [==============================] - 0s 20ms/step - loss: 1.4830 - accuracy: 0.3694 - val_loss: 1.4979 - val_accuracy: 0.5417
Epoch 235/1000
2/2 [==============================] - 0s 20ms/step - loss: 1.5099 - accuracy: 0.3784 - val_loss: 1.4952 - val_accuracy: 0.5417
Epoch 236/1000
2/2 [==============================] - 0s 24ms/step - loss: 1.4329 - accuracy: 0.3694 - val_loss: 1.4919 - val_accuracy: 0.5417
Epoch 237/1000

2/2 [==============================] - 0s 21ms/step - loss: 1.3048 - accuracy: 0.5135 - val_loss: 1.2120 - val_accuracy: 0.6042
Epoch 345/1000
2/2 [==============================] - 0s 20ms/step - loss: 1.2915 - accuracy: 0.5405 - val_loss: 1.2076 - val_accuracy: 0.6042
Epoch 346/1000
2/2 [==============================] - 0s 24ms/step - loss: 1.2906 - accuracy: 0.4955 - val_loss: 1.2027 - val_accuracy: 0.6042
Epoch 347/1000
2/2 [==============================] - 0s 20ms/step - loss: 1.2642 - accuracy: 0.5676 - val_loss: 1.1991 - val_accuracy: 0.6042
Epoch 348/1000
2/2 [==============================] - 0s 24ms/step - loss: 1.2566 - accuracy: 0.5495 - val_loss: 1.1963 - val_accuracy: 0.6042
Epoch 349/1000
2/2 [==============================] - 0s 44ms/step - loss: 1.2981 - accuracy: 0.5045 - val_loss: 1.1934 - val_accuracy: 0.6042
Epoch 350/1000
2/2 [==============================] - 0s 21ms/step - loss: 1.2486 - accuracy: 0.5225 - val_loss: 1.1907 - val_accuracy: 0.6042
Epoch 351/1000

2/2 [==============================] - 0s 21ms/step - loss: 1.0683 - accuracy: 0.6036 - val_loss: 0.9938 - val_accuracy: 0.6458
Epoch 459/1000
2/2 [==============================] - 0s 20ms/step - loss: 1.0510 - accuracy: 0.6126 - val_loss: 0.9931 - val_accuracy: 0.6458
Epoch 460/1000
2/2 [==============================] - 0s 44ms/step - loss: 1.0810 - accuracy: 0.6126 - val_loss: 0.9940 - val_accuracy: 0.6667
Epoch 461/1000
2/2 [==============================] - 0s 22ms/step - loss: 1.0561 - accuracy: 0.6306 - val_loss: 0.9910 - val_accuracy: 0.6667
Epoch 462/1000
2/2 [==============================] - 0s 22ms/step - loss: 1.0918 - accuracy: 0.5856 - val_loss: 0.9890 - val_accuracy: 0.6458
Epoch 463/1000
2/2 [==============================] - 0s 20ms/step - loss: 1.1402 - accuracy: 0.6036 - val_loss: 0.9950 - val_accuracy: 0.6667
Epoch 464/1000
2/2 [==============================] - 0s 25ms/step - loss: 1.0174 - accuracy: 0.6577 - val_loss: 0.9920 - val_accuracy: 0.6458
Epoch 465/1000

2/2 [==============================] - 0s 41ms/step - loss: 1.0737 - accuracy: 0.6486 - val_loss: 0.9223 - val_accuracy: 0.6667
Epoch 573/1000
2/2 [==============================] - 0s 24ms/step - loss: 1.1138 - accuracy: 0.5676 - val_loss: 0.9235 - val_accuracy: 0.6875
Epoch 574/1000
2/2 [==============================] - 0s 47ms/step - loss: 1.0188 - accuracy: 0.6396 - val_loss: 0.9177 - val_accuracy: 0.6875
Epoch 575/1000
2/2 [==============================] - 0s 26ms/step - loss: 0.9738 - accuracy: 0.6757 - val_loss: 0.9236 - val_accuracy: 0.6875
Epoch 576/1000
2/2 [==============================] - 0s 25ms/step - loss: 0.9582 - accuracy: 0.6396 - val_loss: 0.9259 - val_accuracy: 0.6667
Epoch 577/1000
2/2 [==============================] - 0s 25ms/step - loss: 1.0636 - accuracy: 0.6396 - val_loss: 0.9341 - val_accuracy: 0.6667
Epoch 578/1000
2/2 [==============================] - 0s 18ms/step - loss: 0.9513 - accuracy: 0.6306 - val_loss: 0.9259 - val_accuracy: 0.6875
Epoch 579/1000

2/2 [==============================] - 0s 18ms/step - loss: 0.8719 - accuracy: 0.6757 - val_loss: 0.8851 - val_accuracy: 0.6875
Epoch 687/1000
2/2 [==============================] - 0s 22ms/step - loss: 0.9132 - accuracy: 0.6667 - val_loss: 0.8784 - val_accuracy: 0.6875
Epoch 688/1000
2/2 [==============================] - 0s 42ms/step - loss: 0.8772 - accuracy: 0.6757 - val_loss: 0.8738 - val_accuracy: 0.7083
Epoch 689/1000
2/2 [==============================] - 0s 22ms/step - loss: 0.9800 - accuracy: 0.6396 - val_loss: 0.8878 - val_accuracy: 0.7083
Epoch 690/1000
2/2 [==============================] - 0s 18ms/step - loss: 1.0445 - accuracy: 0.6396 - val_loss: 0.8884 - val_accuracy: 0.6875
Epoch 691/1000
2/2 [==============================] - 0s 24ms/step - loss: 0.9147 - accuracy: 0.6577 - val_loss: 0.8869 - val_accuracy: 0.6875
Epoch 692/1000
2/2 [==============================] - 0s 23ms/step - loss: 1.0254 - accuracy: 0.6216 - val_loss: 0.8970 - val_accuracy: 0.6875
Epoch 693/1000

2/2 [==============================] - 0s 22ms/step - loss: 0.9832 - accuracy: 0.7117 - val_loss: 0.8768 - val_accuracy: 0.6875
Epoch 801/1000
2/2 [==============================] - 0s 22ms/step - loss: 0.8637 - accuracy: 0.6757 - val_loss: 0.8836 - val_accuracy: 0.6875
Epoch 802/1000
2/2 [==============================] - 0s 20ms/step - loss: 0.8510 - accuracy: 0.6937 - val_loss: 0.8760 - val_accuracy: 0.6875
Epoch 803/1000
2/2 [==============================] - 0s 45ms/step - loss: 0.8675 - accuracy: 0.6757 - val_loss: 0.8710 - val_accuracy: 0.6875
Epoch 804/1000
2/2 [==============================] - 0s 20ms/step - loss: 0.9022 - accuracy: 0.7117 - val_loss: 0.8738 - val_accuracy: 0.6875
Epoch 805/1000
2/2 [==============================] - 0s 19ms/step - loss: 0.7869 - accuracy: 0.7207 - val_loss: 0.8749 - val_accuracy: 0.7083
Epoch 806/1000
2/2 [==============================] - 0s 20ms/step - loss: 0.9751 - accuracy: 0.6667 - val_loss: 0.8938 - val_accuracy: 0.6875
Epoch 807/1000

2/2 [==============================] - 0s 21ms/step - loss: 0.8649 - accuracy: 0.6847 - val_loss: 0.8504 - val_accuracy: 0.7083
Epoch 915/1000
2/2 [==============================] - 0s 22ms/step - loss: 0.8653 - accuracy: 0.7027 - val_loss: 0.8580 - val_accuracy: 0.6875
Epoch 916/1000
2/2 [==============================] - 0s 20ms/step - loss: 0.8509 - accuracy: 0.7027 - val_loss: 0.8597 - val_accuracy: 0.7083
Epoch 917/1000
2/2 [==============================] - 0s 31ms/step - loss: 1.0046 - accuracy: 0.6847 - val_loss: 0.8640 - val_accuracy: 0.6875
Epoch 918/1000
2/2 [==============================] - 0s 33ms/step - loss: 0.8127 - accuracy: 0.6847 - val_loss: 0.8628 - val_accuracy: 0.6875
Epoch 919/1000
2/2 [==============================] - 0s 33ms/step - loss: 0.8622 - accuracy: 0.6847 - val_loss: 0.8705 - val_accuracy: 0.6875
Epoch 920/1000
2/2 [==============================] - 0s 62ms/step - loss: 0.8698 - accuracy: 0.6577 - val_loss: 0.8733 - val_accuracy: 0.6875
Epoch 921/1000

training accuracy is very high and testing is low = Over fitting

training accuracy is low and testing is high = Under fitting

training accuracy and training is approximately = good
### Fine Tuning Criteria
1. Change the random_state to some other value
2. Add hidden layers
3. Adding drop out layers
4. Adding your custom learning rate
5. Changing the batch size as well as optimizer
6. Adding some more data

Different optimizers, other than gradient descent, rmsprop and difference between them

<0.5 - Worst Model

>0.5 to <0.6 - Below Avg Model

>0.6 to <0.7 - Avg Model

>0.7 to <0.8 - Above Avg Model

>8 to <8.7 - Good Model

>8.5 to <9.5 - Best Model

In [31]:
yp = categorical.predict(sc.transform([[540,28.5,31,34,10.744,6.562]]))

In [32]:
yp

array([[1.5484523e-03, 8.9617014e-02, 5.7186925e-01, 7.4852563e-02,
        2.0309126e-01, 3.0958845e-04, 5.8711812e-02]], dtype=float32)

In [33]:
yp>0.5

array([[False, False,  True, False, False, False, False]])

In [1]:
#yp = [0,0,1,0,0,0,0]

In [35]:
yp = categorical.predict_classes(sc.transform([[60,17.5,19,21.3,8.3922,20.9181]]))

/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [36]:
yp

array([2])

In [40]:
yp = categorical.predict(sc.transform([[20,17.5,42.3,134.3,8.3922,0.9181]]))

In [43]:
yp

array([[1.000000e+00, 0.000000e+00, 0.000000e+00, 4.027892e-35,
        0.000000e+00, 0.000000e+00, 0.000000e+00]], dtype=float32)

In [55]:
yp = np.argmax(yp) #[0,0,0,0,1,0]

In [46]:
index = ["bream", "parkki", "perch", "pike", "roach", "smelt", "whitefish"]

In [48]:
index[yp]

'bream'

In [49]:
prediction = index[yp]

In [50]:
prediction

'bream'

In [51]:
a = np.array([1,2,7,8,10])

In [52]:
a

array([ 1,  2,  7,  8, 10])

In [53]:
np.argmax(a)

4